# Generated by Django 5.2.3 on 2026-07-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_achievementcategory_education_remove_step_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
